# coding: utf-8

"""
    OOXML Automation

    This API helps users convert Excel and Powerpoint documents into rich, live dashboards and stories.  # noqa: E501

    The version of the OpenAPI document: 0.1.0-no-tags
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ChartRowCollections(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name_format_type': 'int',
        'axis_id': 'str',
        'chart_data_id': 'str',
        'id': 'str'
    }

    attribute_map = {
        'name_format_type': 'nameFormatType',
        'axis_id': 'axisId',
        'chart_data_id': 'chartDataId',
        'id': 'id'
    }

    def __init__(self, name_format_type=None, axis_id=None, chart_data_id=None, id=None):  # noqa: E501
        """ChartRowCollections - a model defined in OpenAPI"""  # noqa: E501

        self._name_format_type = None
        self._axis_id = None
        self._chart_data_id = None
        self._id = None
        self.discriminator = None

        if name_format_type is not None:
            self.name_format_type = name_format_type
        self.axis_id = axis_id
        self.chart_data_id = chart_data_id
        if id is not None:
            self.id = id

    @property
    def name_format_type(self):
        """Gets the name_format_type of this ChartRowCollections.  # noqa: E501


        :return: The name_format_type of this ChartRowCollections.  # noqa: E501
        :rtype: int
        """
        return self._name_format_type

    @name_format_type.setter
    def name_format_type(self, name_format_type):
        """Sets the name_format_type of this ChartRowCollections.


        :param name_format_type: The name_format_type of this ChartRowCollections.  # noqa: E501
        :type: int
        """

        self._name_format_type = name_format_type

    @property
    def axis_id(self):
        """Gets the axis_id of this ChartRowCollections.  # noqa: E501


        :return: The axis_id of this ChartRowCollections.  # noqa: E501
        :rtype: str
        """
        return self._axis_id

    @axis_id.setter
    def axis_id(self, axis_id):
        """Sets the axis_id of this ChartRowCollections.


        :param axis_id: The axis_id of this ChartRowCollections.  # noqa: E501
        :type: str
        """

        self._axis_id = axis_id

    @property
    def chart_data_id(self):
        """Gets the chart_data_id of this ChartRowCollections.  # noqa: E501


        :return: The chart_data_id of this ChartRowCollections.  # noqa: E501
        :rtype: str
        """
        return self._chart_data_id

    @chart_data_id.setter
    def chart_data_id(self, chart_data_id):
        """Sets the chart_data_id of this ChartRowCollections.


        :param chart_data_id: The chart_data_id of this ChartRowCollections.  # noqa: E501
        :type: str
        """

        self._chart_data_id = chart_data_id

    @property
    def id(self):
        """Gets the id of this ChartRowCollections.  # noqa: E501


        :return: The id of this ChartRowCollections.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ChartRowCollections.


        :param id: The id of this ChartRowCollections.  # noqa: E501
        :type: str
        """

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChartRowCollections):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
