# coding: utf-8

"""
    OOXML Automation

    This API helps users convert Excel and Powerpoint documents into rich, live dashboards and stories.  # noqa: E501

    The version of the OpenAPI document: 0.1.0-no-tags
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class SharedEffectAttributesDetails(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'effect_type_id': 'int',
        'attributes_json': 'str',
        'effect_id': 'str',
        'effect': 'SharedEffectsDetails',
        'fill_map': 'SharedFillMapDetails',
        'id': 'str',
        'date_created': 'datetime',
        'user_created': 'str',
        'date_modified': 'datetime',
        'user_modified': 'str'
    }

    attribute_map = {
        'effect_type_id': 'effectTypeId',
        'attributes_json': 'attributesJson',
        'effect_id': 'effectId',
        'effect': 'effect',
        'fill_map': 'fillMap',
        'id': 'id',
        'date_created': 'dateCreated',
        'user_created': 'userCreated',
        'date_modified': 'dateModified',
        'user_modified': 'userModified'
    }

    def __init__(self, effect_type_id=None, attributes_json=None, effect_id=None, effect=None, fill_map=None, id=None, date_created=None, user_created=None, date_modified=None, user_modified=None):  # noqa: E501
        """SharedEffectAttributesDetails - a model defined in OpenAPI"""  # noqa: E501

        self._effect_type_id = None
        self._attributes_json = None
        self._effect_id = None
        self._effect = None
        self._fill_map = None
        self._id = None
        self._date_created = None
        self._user_created = None
        self._date_modified = None
        self._user_modified = None
        self.discriminator = None

        if effect_type_id is not None:
            self.effect_type_id = effect_type_id
        self.attributes_json = attributes_json
        self.effect_id = effect_id
        if effect is not None:
            self.effect = effect
        if fill_map is not None:
            self.fill_map = fill_map
        if id is not None:
            self.id = id
        if date_created is not None:
            self.date_created = date_created
        if user_created is not None:
            self.user_created = user_created
        if date_modified is not None:
            self.date_modified = date_modified
        if user_modified is not None:
            self.user_modified = user_modified

    @property
    def effect_type_id(self):
        """Gets the effect_type_id of this SharedEffectAttributesDetails.  # noqa: E501


        :return: The effect_type_id of this SharedEffectAttributesDetails.  # noqa: E501
        :rtype: int
        """
        return self._effect_type_id

    @effect_type_id.setter
    def effect_type_id(self, effect_type_id):
        """Sets the effect_type_id of this SharedEffectAttributesDetails.


        :param effect_type_id: The effect_type_id of this SharedEffectAttributesDetails.  # noqa: E501
        :type: int
        """

        self._effect_type_id = effect_type_id

    @property
    def attributes_json(self):
        """Gets the attributes_json of this SharedEffectAttributesDetails.  # noqa: E501


        :return: The attributes_json of this SharedEffectAttributesDetails.  # noqa: E501
        :rtype: str
        """
        return self._attributes_json

    @attributes_json.setter
    def attributes_json(self, attributes_json):
        """Sets the attributes_json of this SharedEffectAttributesDetails.


        :param attributes_json: The attributes_json of this SharedEffectAttributesDetails.  # noqa: E501
        :type: str
        """

        self._attributes_json = attributes_json

    @property
    def effect_id(self):
        """Gets the effect_id of this SharedEffectAttributesDetails.  # noqa: E501


        :return: The effect_id of this SharedEffectAttributesDetails.  # noqa: E501
        :rtype: str
        """
        return self._effect_id

    @effect_id.setter
    def effect_id(self, effect_id):
        """Sets the effect_id of this SharedEffectAttributesDetails.


        :param effect_id: The effect_id of this SharedEffectAttributesDetails.  # noqa: E501
        :type: str
        """

        self._effect_id = effect_id

    @property
    def effect(self):
        """Gets the effect of this SharedEffectAttributesDetails.  # noqa: E501


        :return: The effect of this SharedEffectAttributesDetails.  # noqa: E501
        :rtype: SharedEffectsDetails
        """
        return self._effect

    @effect.setter
    def effect(self, effect):
        """Sets the effect of this SharedEffectAttributesDetails.


        :param effect: The effect of this SharedEffectAttributesDetails.  # noqa: E501
        :type: SharedEffectsDetails
        """

        self._effect = effect

    @property
    def fill_map(self):
        """Gets the fill_map of this SharedEffectAttributesDetails.  # noqa: E501


        :return: The fill_map of this SharedEffectAttributesDetails.  # noqa: E501
        :rtype: SharedFillMapDetails
        """
        return self._fill_map

    @fill_map.setter
    def fill_map(self, fill_map):
        """Sets the fill_map of this SharedEffectAttributesDetails.


        :param fill_map: The fill_map of this SharedEffectAttributesDetails.  # noqa: E501
        :type: SharedFillMapDetails
        """

        self._fill_map = fill_map

    @property
    def id(self):
        """Gets the id of this SharedEffectAttributesDetails.  # noqa: E501


        :return: The id of this SharedEffectAttributesDetails.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SharedEffectAttributesDetails.


        :param id: The id of this SharedEffectAttributesDetails.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def date_created(self):
        """Gets the date_created of this SharedEffectAttributesDetails.  # noqa: E501


        :return: The date_created of this SharedEffectAttributesDetails.  # noqa: E501
        :rtype: datetime
        """
        return self._date_created

    @date_created.setter
    def date_created(self, date_created):
        """Sets the date_created of this SharedEffectAttributesDetails.


        :param date_created: The date_created of this SharedEffectAttributesDetails.  # noqa: E501
        :type: datetime
        """

        self._date_created = date_created

    @property
    def user_created(self):
        """Gets the user_created of this SharedEffectAttributesDetails.  # noqa: E501


        :return: The user_created of this SharedEffectAttributesDetails.  # noqa: E501
        :rtype: str
        """
        return self._user_created

    @user_created.setter
    def user_created(self, user_created):
        """Sets the user_created of this SharedEffectAttributesDetails.


        :param user_created: The user_created of this SharedEffectAttributesDetails.  # noqa: E501
        :type: str
        """

        self._user_created = user_created

    @property
    def date_modified(self):
        """Gets the date_modified of this SharedEffectAttributesDetails.  # noqa: E501


        :return: The date_modified of this SharedEffectAttributesDetails.  # noqa: E501
        :rtype: datetime
        """
        return self._date_modified

    @date_modified.setter
    def date_modified(self, date_modified):
        """Sets the date_modified of this SharedEffectAttributesDetails.


        :param date_modified: The date_modified of this SharedEffectAttributesDetails.  # noqa: E501
        :type: datetime
        """

        self._date_modified = date_modified

    @property
    def user_modified(self):
        """Gets the user_modified of this SharedEffectAttributesDetails.  # noqa: E501


        :return: The user_modified of this SharedEffectAttributesDetails.  # noqa: E501
        :rtype: str
        """
        return self._user_modified

    @user_modified.setter
    def user_modified(self, user_modified):
        """Sets the user_modified of this SharedEffectAttributesDetails.


        :param user_modified: The user_modified of this SharedEffectAttributesDetails.  # noqa: E501
        :type: str
        """

        self._user_modified = user_modified

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SharedEffectAttributesDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
