# coding: utf-8

"""
    OOXML Automation

    This API helps users convert Excel and Powerpoint documents into rich, live dashboards and stories.  # noqa: E501

    The version of the OpenAPI document: 0.1.0-no-tags
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class SharedFillMap(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'fill_type_id': 'int',
        'shape_id': 'str',
        'connector_id': 'str',
        'effect_attribute_id': 'str',
        'table_cell_id': 'str',
        'theme_background_fill_id': 'str',
        'theme_fill_id': 'str',
        'id': 'str'
    }

    attribute_map = {
        'fill_type_id': 'fillTypeId',
        'shape_id': 'shapeId',
        'connector_id': 'connectorId',
        'effect_attribute_id': 'effectAttributeId',
        'table_cell_id': 'tableCellId',
        'theme_background_fill_id': 'themeBackgroundFillId',
        'theme_fill_id': 'themeFillId',
        'id': 'id'
    }

    def __init__(self, fill_type_id=None, shape_id=None, connector_id=None, effect_attribute_id=None, table_cell_id=None, theme_background_fill_id=None, theme_fill_id=None, id=None):  # noqa: E501
        """SharedFillMap - a model defined in OpenAPI"""  # noqa: E501

        self._fill_type_id = None
        self._shape_id = None
        self._connector_id = None
        self._effect_attribute_id = None
        self._table_cell_id = None
        self._theme_background_fill_id = None
        self._theme_fill_id = None
        self._id = None
        self.discriminator = None

        if fill_type_id is not None:
            self.fill_type_id = fill_type_id
        self.shape_id = shape_id
        self.connector_id = connector_id
        self.effect_attribute_id = effect_attribute_id
        self.table_cell_id = table_cell_id
        self.theme_background_fill_id = theme_background_fill_id
        self.theme_fill_id = theme_fill_id
        if id is not None:
            self.id = id

    @property
    def fill_type_id(self):
        """Gets the fill_type_id of this SharedFillMap.  # noqa: E501


        :return: The fill_type_id of this SharedFillMap.  # noqa: E501
        :rtype: int
        """
        return self._fill_type_id

    @fill_type_id.setter
    def fill_type_id(self, fill_type_id):
        """Sets the fill_type_id of this SharedFillMap.


        :param fill_type_id: The fill_type_id of this SharedFillMap.  # noqa: E501
        :type: int
        """

        self._fill_type_id = fill_type_id

    @property
    def shape_id(self):
        """Gets the shape_id of this SharedFillMap.  # noqa: E501


        :return: The shape_id of this SharedFillMap.  # noqa: E501
        :rtype: str
        """
        return self._shape_id

    @shape_id.setter
    def shape_id(self, shape_id):
        """Sets the shape_id of this SharedFillMap.


        :param shape_id: The shape_id of this SharedFillMap.  # noqa: E501
        :type: str
        """

        self._shape_id = shape_id

    @property
    def connector_id(self):
        """Gets the connector_id of this SharedFillMap.  # noqa: E501


        :return: The connector_id of this SharedFillMap.  # noqa: E501
        :rtype: str
        """
        return self._connector_id

    @connector_id.setter
    def connector_id(self, connector_id):
        """Sets the connector_id of this SharedFillMap.


        :param connector_id: The connector_id of this SharedFillMap.  # noqa: E501
        :type: str
        """

        self._connector_id = connector_id

    @property
    def effect_attribute_id(self):
        """Gets the effect_attribute_id of this SharedFillMap.  # noqa: E501


        :return: The effect_attribute_id of this SharedFillMap.  # noqa: E501
        :rtype: str
        """
        return self._effect_attribute_id

    @effect_attribute_id.setter
    def effect_attribute_id(self, effect_attribute_id):
        """Sets the effect_attribute_id of this SharedFillMap.


        :param effect_attribute_id: The effect_attribute_id of this SharedFillMap.  # noqa: E501
        :type: str
        """

        self._effect_attribute_id = effect_attribute_id

    @property
    def table_cell_id(self):
        """Gets the table_cell_id of this SharedFillMap.  # noqa: E501


        :return: The table_cell_id of this SharedFillMap.  # noqa: E501
        :rtype: str
        """
        return self._table_cell_id

    @table_cell_id.setter
    def table_cell_id(self, table_cell_id):
        """Sets the table_cell_id of this SharedFillMap.


        :param table_cell_id: The table_cell_id of this SharedFillMap.  # noqa: E501
        :type: str
        """

        self._table_cell_id = table_cell_id

    @property
    def theme_background_fill_id(self):
        """Gets the theme_background_fill_id of this SharedFillMap.  # noqa: E501


        :return: The theme_background_fill_id of this SharedFillMap.  # noqa: E501
        :rtype: str
        """
        return self._theme_background_fill_id

    @theme_background_fill_id.setter
    def theme_background_fill_id(self, theme_background_fill_id):
        """Sets the theme_background_fill_id of this SharedFillMap.


        :param theme_background_fill_id: The theme_background_fill_id of this SharedFillMap.  # noqa: E501
        :type: str
        """

        self._theme_background_fill_id = theme_background_fill_id

    @property
    def theme_fill_id(self):
        """Gets the theme_fill_id of this SharedFillMap.  # noqa: E501


        :return: The theme_fill_id of this SharedFillMap.  # noqa: E501
        :rtype: str
        """
        return self._theme_fill_id

    @theme_fill_id.setter
    def theme_fill_id(self, theme_fill_id):
        """Sets the theme_fill_id of this SharedFillMap.


        :param theme_fill_id: The theme_fill_id of this SharedFillMap.  # noqa: E501
        :type: str
        """

        self._theme_fill_id = theme_fill_id

    @property
    def id(self):
        """Gets the id of this SharedFillMap.  # noqa: E501


        :return: The id of this SharedFillMap.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SharedFillMap.


        :param id: The id of this SharedFillMap.  # noqa: E501
        :type: str
        """

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SharedFillMap):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
